// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "softek-rimac-project",
    "version": "1"
  },
  "paths": {
    "/people": {
      "get": {
        "summary": "getPeople",
        "description": "",
        "operationId": "getPeople.get./people",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      },
      "post": {
        "summary": "createPeople",
        "description": "",
        "operationId": "createPeople.post./people",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/People"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/people/{id}": {
      "get": {
        "summary": "getByIdPeople",
        "description": "",
        "operationId": "getByIdPeople.get./people/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      },
      "put": {
        "summary": "updatePeople",
        "description": "",
        "operationId": "updatePeople.put./people/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/People"
            }
          },
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      },
      "delete": {
        "summary": "deletePeople",
        "description": "",
        "operationId": "deletePeople.delete./people/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {
    "People": {
      "properties": {
        "nombre": {
          "title": "People.nombre",
          "type": "string"
        },
        "altura": {
          "title": "People.altura",
          "type": "number"
        },
        "masa": {
          "title": "People.masa",
          "type": "number"
        },
        "color_cabello": {
          "title": "People.color_cabello",
          "type": "string"
        },
        "color_piel": {
          "title": "People.color_piel",
          "type": "string"
        },
        "color_ojos": {
          "title": "People.color_ojos",
          "type": "string"
        },
        "fecha_nacimiento": {
          "title": "People.fecha_nacimiento",
          "type": "string"
        },
        "genero": {
          "title": "People.genero",
          "type": "string"
        }
      },
      "required": [
        "nombre",
        "altura",
        "masa",
        "color_cabello",
        "color_piel",
        "color_ojos",
        "fecha_nacimiento",
        "genero"
      ],
      "additionalProperties": false,
      "title": "People",
      "type": "object"
    }
  },
  "securityDefinitions": {}
};